module.exports = {
    assets: require("./assets"),
    auth: require("./auth"),
    authenticate: require("./authenticate"),
    authorize: require("./authorize"),
    body: require("./body"),
    compression: require("./compression"),
    cors: require("./cors"),
    docs: require("./docs"),
    http: require("./http"),
    i18n: require("./i18n"),
    json: require("./json"),
    logger: require("./logger"),
    notFound: require("./notFound"),
    rates: require("./rates"),
    security: require("./security"),
    serverError: require("./serverError"),
    token: require("./token"),
    assets: require("./assets"),
    views: require("./views"),
    setMaxHits: require("dotapp/middlewares/setMaxHits"),
}
